
# ModLoader
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# The mod
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# Issue tracker
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="goom_icon.png"

# A text field displayed in the mod UI
credits="Special thanks to ✨ filqh ✨"

# A text field displayed in the mod UI
authors="${mod_authors}"

# The description text for the mod
description='''${mod_description}

✓ Abstract inventory slot matching
✓ User-friendly input utilities
✓ Basic scheduling system
✓ A few tediously-specific events'''

# Dependency - Forge
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependency - Minecraft
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"